name: pytorch-gpu
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - pandas
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - pip
  - pip:
    - opencv-python
